#!/usr/bin/env php
<?php

declare(strict_types=1);

define('BASE_PATH', realpath(__DIR__ . '/..'));

$options = getopt('', [
    'source::',
    'index::',
    'output::',
    'category::',
    'include-dangerous',
    'min-size::',
    'max-size::',
]);

$sourceDir = resolve_path($options['source'] ?? 'storage/textfiles/bbs');
$indexFile = resolve_path($options['index'] ?? 'storage/textfiles/bbs/index.html');
$outputSql = resolve_path($options['output'] ?? 'storage/exports/textfiles_bbs_import.sql');
$outputReport = preg_replace('/\.sql$/i', '_report.txt', $outputSql) ?: ($outputSql . '_report.txt');
$categoryPath = trim((string) ($options['category'] ?? 'text-archives/bulletin-board-system'), '/');

$includeDangerous = array_key_exists('include-dangerous', $options);
$minSize = isset($options['min-size']) ? max(0, (int) $options['min-size']) : 0;
$maxSize = isset($options['max-size']) ? max(0, (int) $options['max-size']) : PHP_INT_MAX;

echo "Resolved paths:\n";
echo "  Source Dir : {$sourceDir}\n";
echo "  Index File : {$indexFile}\n";
echo "  Output SQL : {$outputSql}\n";
echo "  Report TXT : {$outputReport}\n";
echo "  Category   : {$categoryPath}\n\n";

if (!is_dir($sourceDir)) {
    fwrite(STDERR, "Source directory not found: {$sourceDir}\n");
    exit(1);
}

if (!is_file($indexFile)) {
    fwrite(STDERR, "Index file not found: {$indexFile}\n");
    exit(1);
}

$indexHtml = file_get_contents($indexFile);
if ($indexHtml === false) {
    fwrite(STDERR, "Could not read index file: {$indexFile}\n");
    exit(1);
}

$entries = parse_index_entries($indexHtml);

$sqlLines = [];
$reportLines = [];
$importedCount = 0;
$skippedCount = 0;

$sqlLines[] = 'START TRANSACTION;';
$sqlLines[] = '';
$sqlLines[] = '-- Textfiles.com BBS import generated by scripts/import_textfiles_bbs.php';
$sqlLines[] = '-- Generated: ' . date('Y-m-d H:i:s');
$sqlLines[] = '-- Category: ' . $categoryPath;
$sqlLines[] = '';
$sqlLines[] = "INSERT INTO import_batches (source_name, batch_label, notes, status, total_categories, total_sites, started_at)";
$sqlLines[] = "VALUES ('textfiles.com', 'BBS Textfiles Import', 'Generated from local textfiles BBS dump', 'completed', 0, 0, NOW());";
$sqlLines[] = '';
$sqlLines[] = 'SET @batch_id = LAST_INSERT_ID();';
$sqlLines[] = '';

$reportLines[] = 'Textfiles.com BBS Import Report';
$reportLines[] = 'Generated: ' . date('Y-m-d H:i:s');
$reportLines[] = 'Source Dir: ' . $sourceDir;
$reportLines[] = 'Index File: ' . $indexFile;
$reportLines[] = 'Category: ' . $categoryPath;
$reportLines[] = '';

foreach ($entries as $entry) {
    $filename = $entry['filename'];
    $title = $entry['title'];
    $bodyDescription = $entry['description'];
    $sizeFromIndex = $entry['size'];

    if (looks_like_collection_directory($filename)) {
        $reportLines[] = '[SKIP DIR] ' . $filename . ' | ' . $bodyDescription;
        $skippedCount++;
        continue;
    }

    if (!$includeDangerous && is_excluded_by_description($bodyDescription)) {
        $reportLines[] = '[SKIP FILTER] ' . $filename . ' | ' . $bodyDescription;
        $skippedCount++;
        continue;
    }

    $filePath = $sourceDir . DIRECTORY_SEPARATOR . $filename;
    if (!is_file($filePath)) {
        $reportLines[] = '[SKIP MISSING] ' . $filename . ' | ' . $bodyDescription;
        $skippedCount++;
        continue;
    }

    $actualSize = filesize($filePath);
    if ($actualSize === false) {
        $actualSize = 0;
    }

    if ($actualSize < $minSize) {
        $reportLines[] = '[SKIP SMALL] ' . $filename . ' | ' . $actualSize . ' bytes | ' . $bodyDescription;
        $skippedCount++;
        continue;
    }

    if ($actualSize > $maxSize) {
        $reportLines[] = '[SKIP LARGE] ' . $filename . ' | ' . $actualSize . ' bytes | ' . $bodyDescription;
        $skippedCount++;
        continue;
    }

    $bodyText = normalize_text_file($filePath);
    if ($bodyText === '') {
        $reportLines[] = '[SKIP EMPTY] ' . $filename . ' | ' . $bodyDescription;
        $skippedCount++;
        continue;
    }

    $slug = unique_slug($title, $filename);
    $shortDescription = 'Historical BBS-era document: ' . $bodyDescription;
    $originalUrl = 'http://textfiles.com/bbs/' . rawurlencode($filename);
    $sourceKey = 'textfiles:bbs:' . $filename;

    $sqlLines[] = '-- ' . $filename . ' (' . $sizeFromIndex . ' bytes in index; ' . $actualSize . ' bytes on disk)';
    $sqlLines[] = 'INSERT INTO sites (';
    $sqlLines[] = '    category_id,';
    $sqlLines[] = '    title,';
    $sqlLines[] = '    slug,';
    $sqlLines[] = '    url,';
    $sqlLines[] = '    normalized_url,';
    $sqlLines[] = '    description,';
    $sqlLines[] = '    original_url,';
    $sqlLines[] = '    status,';
    $sqlLines[] = '    is_active,';
    $sqlLines[] = '    source_type,';
    $sqlLines[] = '    source_key,';
    $sqlLines[] = '    import_batch_id,';
    $sqlLines[] = '    content_type,';
    $sqlLines[] = '    body_text,';
    $sqlLines[] = '    text_source_note,';
    $sqlLines[] = '    text_author,';
    $sqlLines[] = '    is_featured,';
    $sqlLines[] = '    created_at,';
    $sqlLines[] = '    updated_at';
    $sqlLines[] = ')';
    $sqlLines[] = 'SELECT';
    $sqlLines[] = '    c.id,';
    $sqlLines[] = '    ' . sql_quote($title) . ',';
    $sqlLines[] = '    ' . sql_quote($slug) . ',';
    $sqlLines[] = '    NULL,';
    $sqlLines[] = '    NULL,';
    $sqlLines[] = '    ' . sql_quote($shortDescription) . ',';
    $sqlLines[] = '    ' . sql_quote($originalUrl) . ',';
    $sqlLines[] = "    'active',";
    $sqlLines[] = '    1,';
    $sqlLines[] = "    'manual',";
    $sqlLines[] = '    ' . sql_quote($sourceKey) . ',';
    $sqlLines[] = '    @batch_id,';
    $sqlLines[] = "    'text',";
    $sqlLines[] = '    ' . sql_quote($bodyText) . ',';
    $sqlLines[] = "    'Mirrored from textfiles.com for historical preservation.',";
    $sqlLines[] = '    NULL,';
    $sqlLines[] = '    0,';
    $sqlLines[] = '    NOW(),';
    $sqlLines[] = '    NOW()';
    $sqlLines[] = 'FROM categories c';
    $sqlLines[] = 'WHERE c.path = ' . sql_quote($categoryPath);
    $sqlLines[] = '  AND NOT EXISTS (';
    $sqlLines[] = '      SELECT 1';
    $sqlLines[] = '      FROM sites s';
    $sqlLines[] = '      WHERE s.source_key = ' . sql_quote($sourceKey);
    $sqlLines[] = '  );';
    $sqlLines[] = '';

    $reportLines[] = '[IMPORT] ' . $filename . ' | ' . $slug . ' | ' . $bodyDescription;
    $importedCount++;
}

$sqlLines[] = 'UPDATE import_batches';
$sqlLines[] = 'SET total_categories = 1,';
$sqlLines[] = '    total_sites = ' . $importedCount;
$sqlLines[] = 'WHERE id = @batch_id;';
$sqlLines[] = '';
$sqlLines[] = 'COMMIT;';
$sqlLines[] = '';

$reportLines[] = '';
$reportLines[] = 'Imported: ' . $importedCount;
$reportLines[] = 'Skipped: ' . $skippedCount;

ensure_parent_dir($outputSql);
ensure_parent_dir($outputReport);

file_put_contents($outputSql, implode(PHP_EOL, $sqlLines));
file_put_contents($outputReport, implode(PHP_EOL, $reportLines) . PHP_EOL);

echo 'Imported entries: ' . $importedCount . PHP_EOL;
echo 'Skipped entries: ' . $skippedCount . PHP_EOL;
echo 'SQL file written to: ' . $outputSql . PHP_EOL;
echo 'Report written to: ' . $outputReport . PHP_EOL;

function resolve_path(string $path): string
{
    $path = trim($path);

    if ($path === '') {
        return BASE_PATH;
    }

    if (preg_match('/^[A-Za-z]:[\\\\\\/]/', $path) === 1) {
        return $path;
    }

    if (str_starts_with($path, '/') || str_starts_with($path, '\\')) {
        return $path;
    }

    return BASE_PATH . DIRECTORY_SEPARATOR . str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $path);
}

function ensure_parent_dir(string $filePath): void
{
    $dir = dirname($filePath);
    if (!is_dir($dir)) {
        mkdir($dir, 0777, true);
    }
}

function parse_index_entries(string $html): array
{
    $entries = [];

    if (!preg_match_all(
        '~<TR\s+VALIGN=TOP><TD[^>]*><A\s+HREF="([^"]+)">.*?</A>\s*<tab\s+to=T><TD>\s*([0-9]+)?<BR><TD>\s*(.*?)(?=<TR|$)~is',
        $html,
        $matches,
        PREG_SET_ORDER
    )) {
        return $entries;
    }

    foreach ($matches as $match) {
        $filename = trim(html_entity_decode($match[1], ENT_QUOTES | ENT_HTML5, 'UTF-8'));
        $size = isset($match[2]) && $match[2] !== '' ? (int) $match[2] : 0;
        $description = trim(html_entity_decode(strip_tags($match[3]), ENT_QUOTES | ENT_HTML5, 'UTF-8'));

        if ($filename === '' || $description === '') {
            continue;
        }

        $entries[] = [
            'filename' => $filename,
            'size' => $size,
            'description' => $description,
            'title' => $description,
        ];
    }

    return $entries;
}

function looks_like_collection_directory(string $filename): bool
{
    return preg_match('/^[A-Z0-9_-]+$/', $filename) === 1;
}

function is_excluded_by_description(string $description): bool
{
    $needles = [
        'how to crash',
        'crash and destroy',
        'bbs infiltration',
        'hack cbv',
        'bust avoidance',
        'phreak',
        'pirate bbs',
        'break into a bbs',
        'uploaded program alert',
        'scraping the bottom of the barrel',
        'fucking hostile',
    ];

    $haystack = strtolower($description);

    foreach ($needles as $needle) {
        if (str_contains($haystack, $needle)) {
            return true;
        }
    }

    return false;
}

function unique_slug(string $title, string $filename): string
{
    $base = slugify($title);

    if ($base !== 'item') {
        return $base;
    }

    return slugify(pathinfo($filename, PATHINFO_FILENAME));
}

function slugify(string $text): string
{
    $text = trim($text);
    if ($text === '') {
        return 'item';
    }

    $text = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $text) ?: $text;
    $text = strtolower($text);
    $text = preg_replace('/[^a-z0-9]+/', '-', $text) ?? $text;
    $text = trim($text, '-');

    return $text !== '' ? $text : 'item';
}

function normalize_text_file(string $path): string
{
    $raw = file_get_contents($path);
    if ($raw === false || $raw === '') {
        return '';
    }

    if (mb_check_encoding($raw, 'UTF-8')) {
        $text = $raw;
    } else {
        $text = null;

        // Try iconv first for DOS-era encodings
        $iconvEncodings = [
            'IBM437',
            'CP850',
            'Windows-1252',
            'ISO-8859-1',
        ];

        foreach ($iconvEncodings as $encoding) {
            $converted = @iconv($encoding, 'UTF-8//IGNORE', $raw);
            if ($converted !== false && $converted !== '') {
                $text = $converted;
                break;
            }
        }

        // Fallback to mb_convert_encoding for encodings mbstring usually knows
        if ($text === null) {
            $mbEncodings = [
                'Windows-1252',
                'ISO-8859-1',
            ];

            foreach ($mbEncodings as $encoding) {
                try {
                    $converted = @mb_convert_encoding($raw, 'UTF-8', $encoding);
                    if ($converted !== false && $converted !== '') {
                        $text = $converted;
                        break;
                    }
                } catch (\ValueError $e) {
                    // Ignore unsupported encodings in this PHP build
                }
            }
        }

        if ($text === null) {
            $text = $raw;
        }
    }

    $text = str_replace(["\r\n", "\r"], "\n", $text);
    $text = str_replace("\0", '', $text);

    return $text;
}

function sql_quote(string $value): string
{
    return "'" . str_replace(
        ["\\",   "'",   "\n",  "\r",  "\x1a"],
        ["\\\\", "\\'", "\\n", "\\r", "\\Z"],
        $value
    ) . "'";
}