<p>The Internet did not appear all at once, and it was never the invention of a single person or company. It emerged across decades of research, public funding, engineering work, academic cooperation, standard-setting, and cultural experimentation. What we now call the Internet is really the outcome of many overlapping developments: computer networking, packet switching, shared protocols, distributed governance, and later the creation of the World Wide Web. To understand why the modern network looks the way it does, it helps to begin not with websites or apps, but with Cold War research in the United States during the 1960s.</p>

<h2>DARPA and the research climate of the 1960s</h2>
<p>The institutional starting point for Internet history is usually the Advanced Research Projects Agency, established by the United States Department of Defense in 1958 after the shock of Sputnik. ARPA, later renamed DARPA, was designed to fund advanced science and technology work that might be strategically important. Computing soon became one of its most significant areas of interest. In the early 1960s, computers were rare, expensive, and largely isolated from one another. Universities and research laboratories might each have their own large machine, but the idea of connecting those machines together into a shared system was still emerging.</p>
<p>Several thinkers began to imagine more interactive and networked forms of computing. J. C. R. Licklider, one of the most influential early figures, wrote about an “Intergalactic Computer Network” in which people could access data and programs across multiple sites. This was not the Internet yet, but it was a remarkably clear conceptual step towards it. At the same time, the practical question of how such a network might work was being explored by researchers in different countries.</p>
<p>A crucial idea was packet switching. Traditional telephone systems created a dedicated circuit between two points for the duration of a call. For computer data, that model was inefficient. Instead, packet switching broke information into smaller units, sent them across the network independently, and reassembled them at the destination. Paul Baran in the United States and Donald Davies in the United Kingdom both contributed essential work in this area. Packet switching would become one of the foundational ideas behind the Internet.</p>

<h2>ARPANET and the first networked experiments</h2>
<p>In 1969, ARPA funded the creation of ARPANET, the first large-scale operational packet-switched network. The initial nodes were located at UCLA, the Stanford Research Institute, UC Santa Barbara, and the University of Utah. The often-repeated story is that the first attempted message was the word “LOGIN”, but the system crashed after the first two letters, leaving only “LO” transmitted. Whether remembered as a technical milestone or a charming historical anecdote, it marked the start of a new era.</p>
<p>ARPANET’s early role was experimental. It linked researchers and institutions that had already been funded by ARPA, enabling them to share computing resources and exchange ideas. Yet one of its most important effects was social rather than purely technical. Once people were connected, they began to communicate. Email, introduced by Ray Tomlinson in 1971, rapidly became the dominant use of the network. Mailing lists and group discussions followed. In other words, as soon as the infrastructure existed, people used it not just to share machines, but to build communities.</p>
<p>Throughout the 1970s, ARPANET expanded and inspired parallel efforts. Other networks were built for military use, radio communications, or satellite communication. The problem then changed. It was no longer simply how to build one network, but how to connect multiple networks using a common approach.</p>

<h2>TCP/IP and the birth of the Internet</h2>
<p>The breakthrough came with TCP/IP, the protocol suite developed by Vint Cerf and Bob Kahn. The significance of TCP/IP is hard to overstate. It provided a way for separate networks to interoperate without requiring them all to be identical. This is why the Internet is often described as a “network of networks”. Rather than one single centrally owned system, it became an architecture that allowed many independent systems to speak the same language.</p>
<p>On 1 January 1983, ARPANET officially transitioned to TCP/IP. Many historians treat this date as the formal birth of the modern Internet. Around the same period, naming and addressing systems also became more sophisticated. The Domain Name System made it easier for humans to navigate a growing network by replacing raw numerical addressing with memorable names. This was a practical convenience, but it was also culturally significant, because it made the network more legible and more accessible.</p>
<p>Jonathan Postel became one of the great quiet stewards of this era. Through his role in the RFC process and the administration of key registries, he helped hold together a rapidly expanding and increasingly international system. The Internet’s development in these years depended not just on engineering brilliance, but on the shared norms of open documentation, rough consensus, and cooperative administration.</p>

<h2>Academic expansion and early online culture</h2>
<p>In the 1980s, the Internet broadened beyond defence-related research. University and science networks became central. NSFNET, funded by the National Science Foundation, played a major role in this growth by connecting academic institutions and providing a wider backbone for network traffic. The networked world of the 1980s was still relatively specialised, but it was no longer confined to a small defence research environment.</p>
<p>This was also the era in which many enduring forms of online culture took shape. Usenet, created in 1979, allowed distributed discussion through newsgroups. Bulletin board systems let users dial into local systems to exchange messages, files, and software. Internet Relay Chat, introduced in 1988, enabled live text-based discussion across networks. Mailing lists flourished. Much of what later became familiar on the web had already existed in these earlier communities: pseudonyms, moderation, flame wars, FAQs, technical help culture, fandom spaces, and grassroots collaboration.</p>
<p>The important point is that the Internet already had a social life before the web existed. The web later gave this social world a more accessible graphical layer, but the habits and values of networked participation were already developing.</p>

<h2>The World Wide Web</h2>
<p>The Internet and the World Wide Web are not the same thing. The Internet is the underlying network infrastructure and protocol environment. The Web is an application layer built on top of it. That distinction matters historically because the Internet was already well established before the web made it visible to mass audiences.</p>
<p>In 1989, Tim Berners-Lee, working at CERN, proposed a system for linking documents through hypertext over the Internet. His system combined URLs for addressing, HTTP for transferring resources, and HTML for structuring documents. By 1991, the first website and web server were in place. This early web was modest, technical, and largely confined to research communities, but it contained the core elements that would transform public communication.</p>
<p>The web became dramatically more accessible with graphical browsers. NCSA Mosaic, released in 1993, was one of the decisive turning points. It made the web usable by people who were not network specialists. Images could appear inline with text, navigation became easier, and the web began to feel like a public medium rather than a specialist tool. Marc Andreessen, who worked on Mosaic, would later become associated with Netscape, one of the defining companies of the early commercial web.</p>

<h2>The early web: directories, browsers, and homepages</h2>
<p>During the mid-1990s, the web grew explosively. This created a practical challenge: discovery. How were users supposed to find anything? Two broad solutions emerged. The first was the directory model. Yahoo started as a manually curated hierarchical listing of websites. DMOZ, later the Open Directory Project, extended that idea into a vast volunteer-edited taxonomy of the web. These systems reflected a time when the web was still small enough to imagine as something that could be mapped by human editors.</p>
<p>The second solution was search. Systems such as Lycos, Excite, and AltaVista automated discovery by indexing pages and returning results by keyword. AltaVista in particular became emblematic of the pre-Google search era. It was fast, broad, and impressive. Search and directories coexisted for a time, along with portal homepages that tried to be starting points for everything at once: news, mail, weather, search, and navigation.</p>
<p>This was also the golden age of the personal homepage. GeoCities, Angelfire, and Tripod gave ordinary users a place to publish. The result was a web that was messy, expressive, highly individual, and often visually chaotic. It was also one of the most culturally formative periods in Internet history. Millions of people learned what it meant to have a page of their own.</p>

<h2>The dot-com boom and bust</h2>
<p>By the late 1990s, enthusiasm around the web had become financial as well as cultural. Investors poured money into internet companies, often on the assumption that traffic and attention would automatically translate into future profits. This became the dot-com boom. Startups emerged rapidly. Public offerings attracted huge valuations. The web was presented as the future of everything from retail to media to communication.</p>
<p>In 2000 and 2001, much of that speculative bubble collapsed. Many companies failed, and confidence fell sharply. Yet the crash did not end the Internet. On the contrary, it cleared the ground for a more mature phase. Surviving firms such as Amazon remained. Infrastructure improved. Business models became more realistic. The web moved from exuberant experiment towards durable everyday use.</p>

<h2>Google, Wikipedia, and Web 2.0</h2>
<p>Google’s rise changed the structure of web discovery. Its PageRank approach and sparse interface helped it outperform many earlier rivals, and search became increasingly centralised around one gateway. At the same time, Wikipedia demonstrated a different model of knowledge production: open, collaborative, constantly revised, and global in reach. Blogger and other tools made publishing easier. The blogosphere became one of the most distinctive cultural environments of the early 2000s.</p>
<p>This period is often described as Web 2.0. The term was never entirely precise, but it captured a real shift. Websites became more interactive. Users were no longer mainly readers; they were contributors, commenters, uploaders, and participants. Social networks, video sharing, feeds, and platform-based identities became increasingly normal. MySpace, Facebook, YouTube, Flickr, and later Twitter reoriented the web towards participation at scale.</p>

<h2>Platforms, phones, and the centralised web</h2>
<p>In the 2010s, the Internet became more concentrated around a relatively small number of platform companies. Google, Facebook, Amazon, Apple, and Microsoft each came to dominate major parts of the online environment. Search, messaging, social networking, cloud hosting, app ecosystems, and online commerce were increasingly mediated by large central services rather than the open, distributed feel of the earlier web.</p>
<p>The rise of the smartphone accelerated this change. For many users, the Internet stopped feeling like a collection of websites and started feeling like a set of apps. Social feeds, notifications, and algorithmically curated environments became primary interfaces. The old web did not vanish, but it became less visible in everyday life.</p>
<p>This centralisation brought convenience and scale, but it also raised questions about privacy, surveillance, moderation, monopoly power, and the long-term preservation of digital culture. A network that had once been celebrated for decentralisation increasingly revolved around platforms that controlled distribution and visibility.</p>

<h2>The Internet now</h2>
<p>The contemporary Internet is both infrastructure and environment. It supports everything from video streaming and cloud computing to remote work, online education, open-source collaboration, digital activism, gaming, and machine learning services. It is indispensable, but also contested. Governments seek to regulate it. Companies seek to monetise it. Communities seek to preserve their spaces within it. Archivists and historians seek to save what disappears from it.</p>
<p>That last point matters more every year. Large parts of Internet history are fragile. Pages vanish. Services shut down. Links rot. Formats become obsolete. This is why institutions such as the Internet Archive, as well as grassroots preservation groups, play such an important role. The early web was not only innovative; it was ephemeral. Preserving it is part of understanding it.</p>

<h2>Conclusion</h2>
<p>The history of the Internet is not a neat march from one invention to the next. It is the story of overlapping systems: military research, academic networks, public standards, commercial services, volunteer communities, and individual creativity. It begins with DARPA-funded experiments in networking, but it does not stop with protocols. The Internet became what it is because technical systems met human behaviour. People used networks not only to compute, but to speak, argue, organise, publish, archive, trade, joke, and remember.</p>
<p>Seen this way, the Internet is both infrastructure and culture. Its history includes packet switching and TCP/IP, but also Usenet flame wars, personal homepages, search engines, open encyclopedias, browser wars, weblogs, platforms, and preservation efforts. Understanding that longer history makes it easier to see the modern network more clearly. The Internet has changed many times already, and it will change again. What matters is not only where it came from, but what kinds of networked life people continue to build within it.</p>
